Include required Python version in readme
Add note about Python version requirements. Sadly some of us still have Python 2.6 installed by default and have to make accommodations to get 2.7 or newer on.

One of the requirements, numpy, requires Python 2.7 or newer.

```Downloading/unpacking numpy==1.12.0 (from -r requirements.txt (line 3))
  Downloading numpy-1.12.0.zip (4.8MB): 4.8MB downloaded
  Running setup.py egg_info for package numpy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build/numpy/setup.py", line 34, in <module>
        raise RuntimeError("Python version 2.7 or >= 3.4 required.")
    RuntimeError: Python version 2.7 or >= 3.4 required.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build/numpy/setup.py", line 34, in <module>

    raise RuntimeError("Python version 2.7 or >= 3.4 required.")

RuntimeError: Python version 2.7 or >= 3.4 required.
```